os: linux
language: generic
sudo: required
dist: xenial
env:
  - SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2019-07-01-a
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift test --enable-test-discovery
