os: linux
language: generic
sudo: required
dist: xenial
install:
  - SWIFT_VERSION=https://swift.org/builds/development/ubuntu1604/swift-DEVELOPMENT-SNAPSHOT-2019-06-28-a/swift-DEVELOPMENT-SNAPSHOT-2019-06-28-a-ubuntu16.04.tar.gz eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift test --enable-test-discovery
